### ISSUE TITLE
Keine Daten

### ISSUE THREAD

**Issue by Hirates** [renao/sams-integration#7]
Hi. Das Plugin zeigt mir aus irgendeinem Grund keine Daten an. In Elementor kann ich den Shortcode zwar erstellen, aber mir wird nach dem Veröffentlichen nichts angezeigt. 
Ich habe deine Anleitung befolgt, aber leider funktioniert es nicht.

Hier der shortcode [samsfixtures apikey=6b********** teamId=3********]

PS. Wir sind im NWVV, kann es daran liegen?

Grüße Mika

**Comment by renao** [comment]
Hallo Hirates, tut mir Leid, dein Ticket ist bei mir im November komplett untergegangen.

Hattest du es weiter ausprobiert und hat es funktioniert oder besteht das Problem weiterhin?

Ich selbst arbeite für einen Verein im WBV/DVV und das ursprüngliche Plugin hat nun einige Zeit auf dem Buckel, würde das Problem aber sonst auch gerne lösen.

Gib mir doch mal kurz ein Rückmeldung, auch wenn die Saison jetzt möglicherweise schon rum sein könnte :-)

Liebe Grüße

**Comment by Hirates** [comment]
Hi Reano,

Erstmal danke für deine Antwort.
Ich habe mir ein wenig Grübelei gemerkt, dass ich die Sams Server Adresse umstellen musste.
Das Plugin funktioniert wunderbar.

Ich habe nur einen Verbesserungs verschlag.
Wenn der NWVV Sams Server in meinem Fall ausfällt, steht der komplette API Key sichtbar für jeden auf der Website.
Dies stellt für mich ein potenzielles Sicherheitsrisiko dar. Vielleicht kannst du dich damit in einer ruhigen Minute einmal mit auseinandersetzen.

**Comment by renao** [comment]
Oh, das ist ein unschöner Designfehler meinerseits.

Ich überlege mir mal eine Lösung.

**Comment by waffenpanter** [comment]
Gerade wird eh an der Mandantenverwaltung gearbeitet.
Wie mache ich das bei Wordpress, wenn ich über den SSVB.org gehn will? Laut SAMS Wiki ist der Aufruf dann folgender z.B.
https://www.ssvb.org/xml/sportsclubList.xhtml?apiKey=xxxxxxxxxxxxx

**Comment by waffenpanter** [comment]
Okay Problem gelöst.

Gibt es eine Möglichkeit nur die nächsten Spiele anzuzeigen
