### ISSUE TITLE
SAMS Schnittstelle liefert fehlerhafte Daten und Abruf der Bundesliga Daten funktioniert nicht

### ISSUE THREAD

**Issue by exile64** [renao/sams-integration#8]
Auf diesem Weg mal ein dickes Danke für das Plugin. Ich habe ewig nach solch einer Lösung gesucht seit dem das web-splugin mehr oder weniger eingestellt wurde. DANKE

Kleines Problem habe ich. Bei unserer BVV Liga Abfrage steht bei allen Tabellenplätzen "Rang 1". Ist das ein SAMS bzw Abfragefehler oder ähnliches oder liegts evtl. am Plugin?

BG

**Comment by renao** [comment]
Hi, danke für den Hinweis.

Ich habe mal unsere Webseite gecheckt und dort tritt aktuell auch dieser Fehler auf.

Daraufhin habe ich bei Abruf der Rohdaten entdeckt, dass die Schnittstelle für alle Teams einen Eintrag "<place>1</place>" liefert.

Ich versuche mal herauszufinden, wo ich einen Bugreport einstellen kann und melde mich sonst nochmal zurück, wenn ich was neues erfahre.

**Comment by exile64** [comment]
Falls du auch weißt wieso ich keine Daten der 2. BL bekomme nehme ich gerne Tipps an. Für die regionalen Verbände klappt es super, nur VBL will irgendwie nicht :-(

**Comment by renao** [comment]
Ich hatte gesehen, dass sich mittlerweile auch ein paar der Basis-URLs geändert haben.

Wenn es die Zeit hergibt mache ich diese Konfiguration anpassbar, denn mittlerweile wird auch bei uns auf Landesebene das SAMS-System wohl flächendeckend eingesetzt.

Allerdings habe ich gerade bei meinen Tests gegen die Basis-URL dvv-ligen.de/xml/... regelmäßig die Rückmeldung bekommen, dass das Server-Zertifikat nicht gültig sei.
Vielleicht macht das auch gerade noch ungewollte Probleme.

Ich denke ich werde da morgen nochmal genauer reinsehen können 👍

**Comment by exile64** [comment]
Das wäre spitze! Es ist wirklich sehr hilfreich das Plugin um einfach sich die Daten über die API zu ziehen.
Klasse Arbeit! Danke nochmals an dieser Stelle 👍

**Comment by renao** [comment]
Hi @exile64 

wie bisher immer gibt es keine Rückmeldungen von dem "Support" des Herstellers - ich denke wir müssen wohl oder übel erstmal davon ausgehen, dass die Platzierungen ggf. nicht in nächste Zeit gefixt werden.
Sollte ich was hören - wie bereits schon gesagt - geb ich das bekannt.

Ansonsten plane ich gerade das Plugin nochmal "fit für 2024/2025" zu machen - sollte alles wie gewünscht funktionieren, würde ich auch zusehen, dass das Plugin in der WordPress Plugin Bibliothek aufgenommen wird und somit der ganze Aufwand zur Installation nicht mehr so weit vom WordPress Standard abweicht.

Ich mach mir mal ein paar Gedanken und aktualisiere dann hier nach und nach das Repository/Projekt auf GitHub 👍

**Comment by exile64** [comment]
hey @renao 
ja, leider kenne ich das Problem teilweise gut mit der IT dort :-)
Aber ja, ich warte gerne, und wenn das in die WB Plugin Bibliothek integriert wird wäre das super und würde das etwas einfacher/schneller machen. Top!

Hast du evtl. noch einen Hinweis für mich oder Tipp wieso ich die VBL Daten nicht abrufen kann, den regionalen Verband aber schon?

Habe einmal den API-Key vom BVV sowie einen der VBL.

**Comment by renao** [comment]
Kannst du mir die konkreten Ligen einmal nennen?
Dann kann ich das entsprechend einmal selbst ausprobieren.

**Comment by renao** [comment]
Ja, klingt in der Verwendung der Schnittstelle erstmal gut.

Aus irgendwelchen Gründen hat der Hersteller scheinbar unterschiedliche Basis-Adressen je nach Verband/Liga angelegt.
Dafür muss ich mir mal eine gute Lösung ausdenken - könntest du sonst zwischenzeitlich mal folgende URL aufrufen:

https://www.volleyball-bundesliga.de/xml/rankings.xhtml?matchSeriesId=770581327&apiKey=****
Natürlich mit deinem API Key :-)

Kriegst du da eine XML-Datei zurück oder eine Fehlermeldung?

**Comment by exile64** [comment]
@renao 
Ja, die xml Abfrage funktioniert. Bekomme die rankings via XML ausgegeben.

**Comment by renao** [comment]
Alles klar, dann haben wir das Problem schonmal erfasst.

Ich denke mir eine praktikable Lösung aus - vielleicht auch eine, bei der ich nicht von Hand die ganzen URLs pflegen muss _oder_ man jedes mal angeben muss, von welcher Basisadresse die Daten geholt werden sollen.

Der Hersteller macht es mir gerade nicht sehr einfach 😬

**Comment by exile64** [comment]
Kann ich mir gut vorstellen. Verstehe eh nicht wieso es für 3. so "unfreundlich" gemacht wird die Tabellen etc. einbinden zu können.
Ich denke auch das eine manuelle Eingabe der erforderlichen Liga der beste Weg ist. Das sollte ja auch für den Nutzer des Plugins noch machbar sein diese herauszufinden ^^
Vielleicht dann durch verschiedene Shortcodes realisieren die je nach Konfiguration (also Ligaadresse) dann erstellt werden. So könnte ich mir das als Laie vorstellen :D

**Comment by renao** [comment]
Also beispielhaft dann: `[bvv-ranking ...]` , [`vbl-ranking ...]` usw.? 🤔

**Comment by exile64** [comment]
Dieser Verein hier hat auch meines Erachtens nach selbst ein Plugin geschrieben oder schreiben lassen. Vielleicht hilft dir das in irgendeiner Art weiter.

https://www.vc-stralsund.de/wildcats/spielplan/

**Comment by renao** [comment]
Guck ich mir mal an.

Finde die Idee mit den eigenen Shortcodes für die Verbände/Ligen ganz gut. Erspart man dem Nutzer technischen Schnickschnack - finde das jetzt schon relativ "nutzerunfreundlich" diese blöden IDs rauszusuchen und anzugeben.

Habt ihr für diese `matchSeriesIds`eigentlich eine aktuelle Übersicht?
Beim WVV interessiert das leider niemanden und auch dort laufen meine Nachfragen ins Nirvana.

Wenn ich die Daten nämlich irgendwo einfach "einsammeln" könnte, dann könnte hoffentlich auch irgendwann einfach diese blöde ID rausfliegen - aber das sind Schritt 4 und 5 aus heutiger Sicht.

Ich schaue mal was einen Fix bzgl. der URL anbelangt.

**Comment by exile64** [comment]
> Habt ihr für diese `matchSeriesIds`eigentlich eine aktuelle Übersicht? Beim WVV interessiert das leider niemanden und auch dort laufen meine Nachfragen ins Nirvana.

Ich zieh mir die auch nur über die XML Datei oder im besten Falle einfach über die URL der jeweiligen Liga in der Tabelle bzw Mannschaftsseite (oder aus der ical url 😆). 

Eine alternative wäre auch https://volleyball-ergebnisdienst.de/main/index.html
Aber finde deine via Plugin deutlich angenehmer.

**Comment by renao** [comment]
Hallo @exile64 ,

habe lange nichts mehr von mir hören lassen - und in der Zwischenzeit das Plugin mal neu implementiert.

Das Plugin hat das Review auf wordpress.org bestanden und wird demnächst auch im offiziellen Plugin Directory verfügbar sein.

Das bedeutet du kannst dir hier eine Version aus dem Repository ziehen oder einfach auf das Release in den kommenden Tagen warten und es einfach via "Plugin installieren" aus dem Plugin Directory/Marktplatz installieren.

Die Implementierung als Shortcode habe ich nun auch den aktuellen WordPress-Gegebenheiten angepasst und Blöcke für den Gutenberg-Editor erstellt (SAMS Ranking, SAMS Fixtures).
Noch müssen die `MatchSeriesId`, `TeamId` usw. noch von Hand eingetragen werden, aber ich plane noch ein paar Komfortumbauten dahingehend (also ist's aktuell noch ziemlich nah an dem "Un"-Komfort des Shortcodes). Immerhin kannst du jetzt aber die Basis-Adresse des Aufrufes (also bspw. `wvv.sams-server.de` für den WVV) setzen und somit jedem Block eigene Konfigurationen mitgeben (also auch bspw. aus mehreren Verbänden die Tabellen einpflegen).

Vielleicht löst's ja dein Problem? :)

**Comment by exile64** [comment]
Jetzt hatte ich völlig vergessen zu antworten. Erstmal 1000 Dank an dich das du dir die Arbeit gemacht hast. Ich werde das Plugin die nächsten Tage mal testen und dir dann nochmal Bericht erstatten :)

**Comment by renao** [comment]
Hi @exile64
ich gehe davon aus Elementor ist ein Editor Plugin?
Gib mir mal einen Link dazu, bin selbst ehrlicherweise nur für dieses Plugin in den WordPress Gefilden unterwegs - und meine Heimatverein beherbergt auch noch eine ziemlich alte WP Version, sodass ich da sowieso nicht ganz state of the art bin, was WordPress im Allgemeinen angeht.

**Comment by exile64** [comment]
Hey. Ja genau. Elementor ist ein "Baukasten" Editor mit ziemlich vielen Features und auch gut anpassbar. Für uns ist es am einfachsten das alle beteiligten Personen schnell und einfach Dinge realisieren können (Spielberichte etc) ohne jetzt weitere Kenntnisse haben zu müssen.

Wordpress: https://de.wordpress.org/plugins/elementor/
HP: https://elementor.com/

**Comment by renao** [comment]
Hi @exile64 ,

so Ferien sind vorbei, ich habe mich mal eingelesen.
Es gibt eine Möglichkeit bei Elementor Gutenberg Blöcke einzubinden:

https://theplusaddons.com/blog/how-to-display-gutenberg-blocks-in-elementor/

Wäre das eine Lösung?

Alternativ würde mich interessieren, was da sonst so der Standard wäre.
Kann bspw. Elementor besser mit Shortcodes umgehen?

**Comment by exile64** [comment]
Hallo @renao ,
sorry - jetzt hab ich getrödelt mit antworten.
Shortcodes wären eine Alternative korrekt. Elementor kann diese auch problemlos darstellen.
Ich werde trotzdem mal dein vorgeschlagenes Plugin versuchen. Danke dafür :)

**Comment by exile64** [comment]
Grüße, danke erstmal weiterhin für deine Mühe zu dem Plugin <3 :)
Konntest du mal schauen ob du die Shortcodes implementiert bekommen könntest?
Oder im besten Falle sogar als "Elementor" Block/Widget? Je nachdem wie du Zeit hast und dir den Aufwand machen möchtest.

**Comment by renao** [comment]
Hi, ich hatte mir mal Elementor angesehen und da hatte ich in der Dokumentation gelesen, dass Elementor selbst Gutenberg-Blöcke unterstützt 🤔 

Als Fallback-Lösung wäre es natürlich dennoch eine gute Idee die Shortcuts zu implementieren... vielleicht komme ich in der nächsten Zeit dazu 👍
